import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2 className="text-2xl mt-10">Upgrade your Firebase Skills Today</h2>
        <h3 className="mt-10">
          Learn how to use firebase using a real application{" "}
        </h3>
      </main>
    </div>
  );
}
